# Generated by Django 2.0.5 on 2019-06-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190613_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title', 'owner', 'subject']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='owner',
        ),
    ]
