# Generated by Django 2.0.5 on 2019-06-20 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190620_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageitem',
            old_name='image',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='textitem',
            old_name='text',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='content',
            name='module',
            field=models.ForeignKey(limit_choices_to={'model__in': ('text', 'file', 'image', 'video')}, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.Module'),
        ),
    ]
